# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 10:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsible',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleImpl',
            fields=[
                ('responsible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Responsible')),
            ],
            bases=('model.responsible',),
        ),
        migrations.CreateModel(
            name='ResponsibleInit',
            fields=[
                ('responsible_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.Responsible')),
            ],
            bases=('model.responsible',),
        ),
        migrations.AddField(
            model_name='responsible',
            name='cm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Countermeasure'),
        ),
        migrations.AddField(
            model_name='responsible',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='model.Role'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='responsibleImplementer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.ResponsibleImpl'),
        ),
        migrations.AddField(
            model_name='countermeasure',
            name='responsibleInitiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='model.ResponsibleInit'),
        ),
    ]
