# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20171103_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countermeasure',
            name='responsibleImplementer',
        ),
        migrations.RemoveField(
            model_name='countermeasure',
            name='responsibleInitiator',
        ),
    ]
