# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-05 14:36
from __future__ import unicode_literals

import bsi.models.article_extensions
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import enumfields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRevisionValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.ArticleRevision')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BSI',
            fields=[
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.URLPath')),
                ('articleType', enumfields.fields.EnumField(blank=True, enum=bsi.models.article_extensions.BSI_Article_type, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UGA',
            fields=[
                ('url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.URLPath')),
            ],
        ),
        migrations.AddField(
            model_name='bsi',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='is_linked_to', to='bsi.UGA'),
        ),
    ]
