# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-07 04:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BSI',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.Article')),
                ('bsi_id', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UGA',
            fields=[
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='wiki.Article')),
            ],
        ),
        migrations.AddField(
            model_name='bsi',
            name='references',
            field=models.ManyToManyField(blank=True, related_name='is_linked_to', to='bsi.UGA'),
        ),
    ]
