# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-16 21:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bsi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleRevisionValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('revision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='wiki.ArticleRevision')),
                ('validator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
