# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_url', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_of', to='wiki.URLPath', verbose_name=b'archive')),
            ],
        ),
        migrations.CreateModel(
            name='ArchiveTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_archive_of', to='archive.Archive', verbose_name=b'archive parent article')),
                ('urlpath', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urlpath_of', to='wiki.URLPath', verbose_name=b'urlpath to transfer')),
            ],
        ),
    ]
