# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_urlpath_moved_to'),
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivetransaction',
            name='urlpath',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urlpath_of', to='wiki.URLPath', verbose_name=b'urlpath to transfer'),
        ),
    ]
