# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-15 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_url',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='url_of', to='wiki.URLPath', verbose_name='archive'),
        ),
        migrations.AlterField(
            model_name='archivetransaction',
            name='archive_root',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='root_archive_of', to='archive.Archive', verbose_name='archive parent article'),
        ),
        migrations.AlterField(
            model_name='archivetransaction',
            name='urlpath',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urlpath_of', to='wiki.URLPath', verbose_name='urlpath to transfer'),
        ),
    ]
