# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-14 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_archivetransaction_urlpath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivetransaction',
            name='urlpath',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='urlpath_of', to='wiki.URLPath', verbose_name='urlpath to transfer'),
        ),
    ]
