# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-23 09:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('infopage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answer',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a_edited_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='question',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='edited_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='q_edited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
